//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Discount1 { get; set; }
        public Nullable<double> PriceBefore { get; set; }
        public Nullable<double> PriceAfter { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime Date { get; set; }
        public string MoreInfo { get; set; }
        public Nullable<int> Shop_ShopID { get; set; }
        public int TimesReported { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
