//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedItem
    {
        public int PurchasedItemId { get; set; }
        public string ShopName { get; set; }
        public string ItemName { get; set; }
        public double Price { get; set; }
        public bool IsChecked { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public string Category { get; set; }
        public string Contains { get; set; }
        public Nullable<bool> IsHealthy { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
