//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptID { get; set; }
        public string ShopName { get; set; }
        public double Value { get; set; }
        public System.DateTime DatePurchased { get; set; }
        public System.TimeSpan TimePurchased { get; set; }
        public string Content { get; set; }
        public int UserId { get; set; }
    }
}
