//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spending
    {
        public int UserAccountID { get; set; }
        public int WeeklyLimit { get; set; }
        public int YearlyLimit { get; set; }
        public int MonthlyLimit { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
